services:
  - type: web
    name: dmc-trichology-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - fromContext: true
        key: PORT
      - fromContext: true
        key: MONGO_URI
      - fromContext: true
        key: JWT_SECRET
      - fromContext: true
        key: BASE_URL
